### ISSUE TITLE
Incorrect Headings and Body Text in Lecture Files

### ISSUE THREAD

**Issue by hopps76** [aheil/devops#1]
@aheil I found some incorrect headings and body text while studying for tomorrow. I tried to fix it and make a PR, but sadly i am not allowed to ;)

#### In each file there is a wrong heading: 
<img width="211" alt="Screenshot 2023-11-19 at 22 13 46" src="https://github.com/aheil/devops/assets/104462587/5e169ab3-2068-4b10-b2aa-cb90c8e09d4a">

#### Example:
<img width="731" alt="Screenshot 2023-11-19 at 22 15 25" src="https://github.com/aheil/devops/assets/104462587/9295220d-1120-4862-b163-601e605455bb">

#### Also, I found a wrong body text/ dead copy of the VM topic from before
<img width="1302" alt="Screenshot 2023-11-19 at 22 16 11" src="https://github.com/aheil/devops/assets/104462587/01f36f06-ad31-423b-bb2c-25f180754a84">

**Comment by aheil** [comment]
Thanks, appreciate a lot. You need to fork, check-in, push and then create a PR.

**Comment by hopps76** [comment]
@aheil Thanks a lot for your work. https://github.com/aheil/devops/pull/2

**Comment by aheil** [comment]
General review of the content is ongoing.
